name: Health check

on:
  schedule:
    - cron: '45 * * * *'
  
jobs:
  healthcheck:
      runs-on: ubuntu-18.04
      steps:
        - name: Check the deployed service URL
          uses: jtalk/url-health-check-action@v1.5
          with:
            url: https://full-stack-pokemon-cards.herokuapp.com/health
            follow-redirect: no
            max-attempts: 3
            retry-delay: 5s
            retry-all: no